# Configuration for librarian-puppet. For example:
#
forge "http://forge.puppetlabs.com"

mod "puppetlabs/stdlib"
mod "mysql",
  :git => "https://github.com/puppetlabs/puppetlabs-mysql.git"
mod "apache",
  :git => "https://github.com/puppetlabs/puppetlabs-apache.git"
mod "php",
  :git => "https://github.com/example42/puppet-php"
